/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Driver
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('Driver', ['BaseModel',
        function (BaseModel) {
            var Driver = function (obj) {
                if (!obj) {
                    this.name = null;
                    this.phoneNumber = null;
                    this.pictureUrl = null;
                    this.rating = null;
        
                    // Append to variable dictionary
                    this._variableDict['phoneNumber'] = 'phone_number';
                    this._variableDict['pictureUrl'] = 'picture_url';
                } else {
                    this.name = obj.name;
                    this.phoneNumber = obj.phone_number;
                    this.pictureUrl = obj.picture_url;
                    this.rating = obj.rating;
            
                    // Append to variable dictionary
                    this._variableDict['phoneNumber'] = 'phone_number';
                    this._variableDict['pictureUrl'] = 'picture_url';
                }
            }
    
            Driver.prototype = new BaseModel();
            Driver.prototype.constructor = Driver;
        
            /**
             * The first name of the driver.
             *
             * @return {string}
             */
            Driver.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            Driver.prototype.setName = function (value) {
                this.name = value;
            };
        
            /**
             * The formatted phone number for contacting the driver.
             *
             * @return {string}
             */
            Driver.prototype.getPhoneNumber = function () {
                return this.phoneNumber;
            };
        
            /**
             * Setter for PhoneNumber
             * 
             * @param {string} value 
             */
            Driver.prototype.setPhoneNumber = function (value) {
                this.phoneNumber = value;
            };
        
            /**
             * The URL to the photo of the driver.
             *
             * @return {string}
             */
            Driver.prototype.getPictureUrl = function () {
                return this.pictureUrl;
            };
        
            /**
             * Setter for PictureUrl
             * 
             * @param {string} value 
             */
            Driver.prototype.setPictureUrl = function (value) {
                this.pictureUrl = value;
            };
        
            /**
             * The driver's star rating out of 5 stars.
             *
             * @return {double}
             */
            Driver.prototype.getRating = function () {
                return this.rating;
            };
        
            /**
             * Setter for Rating
             * 
             * @param {double} value 
             */
            Driver.prototype.setRating = function (value) {
                this.rating = value;
            };
        
            return Driver;
        }
    ]);

}(angular));
