/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Errors
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('Errors', ['BaseModel',
        function (BaseModel) {
            var Errors = function (obj) {
                if (!obj) {
                    this.code = null;
                    this.status = null;
                    this.title = null;
                } else {
                    this.code = obj.code;
                    this.status = obj.status;
                    this.title = obj.title;
                }
            }
    
            Errors.prototype = new BaseModel();
            Errors.prototype.constructor = Errors;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Errors.prototype.getCode = function () {
                return this.code;
            };
        
            /**
             * Setter for Code
             * 
             * @param {string} value 
             */
            Errors.prototype.setCode = function (value) {
                this.code = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {int}
             */
            Errors.prototype.getStatus = function () {
                return this.status;
            };
        
            /**
             * Setter for Status
             * 
             * @param {int} value 
             */
            Errors.prototype.setStatus = function (value) {
                this.status = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Errors.prototype.getTitle = function () {
                return this.title;
            };
        
            /**
             * Setter for Title
             * 
             * @param {string} value 
             */
            Errors.prototype.setTitle = function (value) {
                this.title = value;
            };
        
            return Errors;
        }
    ]);

}(angular));
