/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Location
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('Location', ['BaseModel',
        function (BaseModel) {
            var Location = function (obj) {
                if (!obj) {
                    this.address = null;
                    this.latitude = null;
                    this.longitude = null;
                } else {
                    this.address = obj.address;
                    this.latitude = obj.latitude;
                    this.longitude = obj.longitude;
                }
            }
    
            Location.prototype = new BaseModel();
            Location.prototype.constructor = Location;
        
            /**
             * The address in user readable form
             *
             * @return {string}
             */
            Location.prototype.getAddress = function () {
                return this.address;
            };
        
            /**
             * Setter for Address
             * 
             * @param {string} value 
             */
            Location.prototype.setAddress = function (value) {
                this.address = value;
            };
        
            /**
             * Latitude component of location.
             *
             * @return {double}
             */
            Location.prototype.getLatitude = function () {
                return this.latitude;
            };
        
            /**
             * Setter for Latitude
             * 
             * @param {double} value 
             */
            Location.prototype.setLatitude = function (value) {
                this.latitude = value;
            };
        
            /**
             * Longitude component of location.
             *
             * @return {double}
             */
            Location.prototype.getLongitude = function () {
                return this.longitude;
            };
        
            /**
             * Setter for Longitude
             * 
             * @param {double} value 
             */
            Location.prototype.setLongitude = function (value) {
                this.longitude = value;
            };
        
            return Location;
        }
    ]);

}(angular));
