/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of PriceEstimateCollection
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('PriceEstimateCollection', ['BaseModel', 'PriceEsitmate',
        function (BaseModel, PriceEsitmate) {
            var PriceEstimateCollection = function (obj) {
                if (!obj) {
                    this.prices = null;
                } else {
                    this.prices = obj.prices.map(function (model) {
                        return new PriceEsitmate(model);
                    });
                }
            }
    
            PriceEstimateCollection.prototype = new BaseModel();
            PriceEstimateCollection.prototype.constructor = PriceEstimateCollection;
        
            /**
             * List of price estimates
             *
             * @return {array}
             */
            PriceEstimateCollection.prototype.getPrices = function () {
                return this.prices;
            };
        
            /**
             * Setter for Prices
             * 
             * @param {array} value 
             */
            PriceEstimateCollection.prototype.setPrices = function (value) {
                this.prices = value;
            };
        
            return PriceEstimateCollection;
        }
    ]);

}(angular));
