/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of RequestMapResponse
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('RequestMapResponse', ['BaseModel',
        function (BaseModel) {
            var RequestMapResponse = function (obj) {
                if (!obj) {
                    this.href = null;
                    this.requestId = null;
        
                    // Append to variable dictionary
                    this._variableDict['requestId'] = 'request_id';
                } else {
                    this.href = obj.href;
                    this.requestId = obj.request_id;
            
                    // Append to variable dictionary
                    this._variableDict['requestId'] = 'request_id';
                }
            }
    
            RequestMapResponse.prototype = new BaseModel();
            RequestMapResponse.prototype.constructor = RequestMapResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            RequestMapResponse.prototype.getHref = function () {
                return this.href;
            };
        
            /**
             * Setter for Href
             * 
             * @param {string} value 
             */
            RequestMapResponse.prototype.setHref = function (value) {
                this.href = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            RequestMapResponse.prototype.getRequestId = function () {
                return this.requestId;
            };
        
            /**
             * Setter for RequestId
             * 
             * @param {string} value 
             */
            RequestMapResponse.prototype.setRequestId = function (value) {
                this.requestId = value;
            };
        
            return RequestMapResponse;
        }
    ]);

}(angular));
