/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SurgeConfirmation
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('SurgeConfirmation', ['BaseModel',
        function (BaseModel) {
            var SurgeConfirmation = function (obj) {
                if (!obj) {
                    this.href = null;
                    this.surgeConfirmationId = null;
        
                    // Append to variable dictionary
                    this._variableDict['surgeConfirmationId'] = 'surge_confirmation_id';
                } else {
                    this.href = obj.href;
                    this.surgeConfirmationId = obj.surge_confirmation_id;
            
                    // Append to variable dictionary
                    this._variableDict['surgeConfirmationId'] = 'surge_confirmation_id';
                }
            }
    
            SurgeConfirmation.prototype = new BaseModel();
            SurgeConfirmation.prototype.constructor = SurgeConfirmation;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SurgeConfirmation.prototype.getHref = function () {
                return this.href;
            };
        
            /**
             * Setter for Href
             * 
             * @param {string} value 
             */
            SurgeConfirmation.prototype.setHref = function (value) {
                this.href = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SurgeConfirmation.prototype.getSurgeConfirmationId = function () {
                return this.surgeConfirmationId;
            };
        
            /**
             * Setter for SurgeConfirmationId
             * 
             * @param {string} value 
             */
            SurgeConfirmation.prototype.setSurgeConfirmationId = function (value) {
                this.surgeConfirmationId = value;
            };
        
            return SurgeConfirmation;
        }
    ]);

}(angular));
