/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of UserActivity
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('UserActivity', ['BaseModel', 'History',
        function (BaseModel, History) {
            var UserActivity = function (obj) {
                if (!obj) {
                    this.count = null;
                    this.history = null;
                    this.limit = null;
                    this.offset = null;
                } else {
                    this.count = obj.count;
                    this.history = obj.history.map(function (model) {
                        return new History(model);
                    });
                    this.limit = obj.limit;
                    this.offset = obj.offset;
                }
            }
    
            UserActivity.prototype = new BaseModel();
            UserActivity.prototype.constructor = UserActivity;
        
            /**
             * Total number of items available.
             *
             * @return {int}
             */
            UserActivity.prototype.getCount = function () {
                return this.count;
            };
        
            /**
             * Setter for Count
             * 
             * @param {int} value 
             */
            UserActivity.prototype.setCount = function (value) {
                this.count = value;
            };
        
            /**
             * Information including the pickup location, dropoff location, request start time, request end time, and distance of requests (in miles), as well as the product type that was requested.
             *
             * @return {array}
             */
            UserActivity.prototype.getHistory = function () {
                return this.history;
            };
        
            /**
             * Setter for History
             * 
             * @param {array} value 
             */
            UserActivity.prototype.setHistory = function (value) {
                this.history = value;
            };
        
            /**
             * Number of items to retrieve (100 max).
             *
             * @return {int}
             */
            UserActivity.prototype.getLimit = function () {
                return this.limit;
            };
        
            /**
             * Setter for Limit
             * 
             * @param {int} value 
             */
            UserActivity.prototype.setLimit = function (value) {
                this.limit = value;
            };
        
            /**
             * Position in pagination.
             *
             * @return {int}
             */
            UserActivity.prototype.getOffset = function () {
                return this.offset;
            };
        
            /**
             * Setter for Offset
             * 
             * @param {int} value 
             */
            UserActivity.prototype.setOffset = function (value) {
                this.offset = value;
            };
        
            return UserActivity;
        }
    ]);

}(angular));
