/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of UserProfile
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('UserProfile', ['BaseModel',
        function (BaseModel) {
            var UserProfile = function (obj) {
                if (!obj) {
                    this.email = null;
                    this.firstName = null;
                    this.lastName = null;
                    this.picture = null;
                    this.promoCode = null;
        
                    // Append to variable dictionary
                    this._variableDict['firstName'] = 'first_name';
                    this._variableDict['lastName'] = 'last_name';
                    this._variableDict['promoCode'] = 'promo_code';
                } else {
                    this.email = obj.email;
                    this.firstName = obj.first_name;
                    this.lastName = obj.last_name;
                    this.picture = obj.picture;
                    this.promoCode = obj.promo_code;
            
                    // Append to variable dictionary
                    this._variableDict['firstName'] = 'first_name';
                    this._variableDict['lastName'] = 'last_name';
                    this._variableDict['promoCode'] = 'promo_code';
                }
            }
    
            UserProfile.prototype = new BaseModel();
            UserProfile.prototype.constructor = UserProfile;
        
            /**
             * Email address of the Uber user
             *
             * @return {string}
             */
            UserProfile.prototype.getEmail = function () {
                return this.email;
            };
        
            /**
             * Setter for Email
             * 
             * @param {string} value 
             */
            UserProfile.prototype.setEmail = function (value) {
                this.email = value;
            };
        
            /**
             * First name of the Uber user.
             *
             * @return {string}
             */
            UserProfile.prototype.getFirstName = function () {
                return this.firstName;
            };
        
            /**
             * Setter for FirstName
             * 
             * @param {string} value 
             */
            UserProfile.prototype.setFirstName = function (value) {
                this.firstName = value;
            };
        
            /**
             * Last name of the Uber user.
             *
             * @return {string}
             */
            UserProfile.prototype.getLastName = function () {
                return this.lastName;
            };
        
            /**
             * Setter for LastName
             * 
             * @param {string} value 
             */
            UserProfile.prototype.setLastName = function (value) {
                this.lastName = value;
            };
        
            /**
             * Image URL of the Uber user.
             *
             * @return {string}
             */
            UserProfile.prototype.getPicture = function () {
                return this.picture;
            };
        
            /**
             * Setter for Picture
             * 
             * @param {string} value 
             */
            UserProfile.prototype.setPicture = function (value) {
                this.picture = value;
            };
        
            /**
             * Promo code of the Uber user.
             *
             * @return {string}
             */
            UserProfile.prototype.getPromoCode = function () {
                return this.promoCode;
            };
        
            /**
             * Setter for PromoCode
             * 
             * @param {string} value 
             */
            UserProfile.prototype.setPromoCode = function (value) {
                this.promoCode = value;
            };
        
            return UserProfile;
        }
    ]);

}(angular));
